import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

def main(): 
    df = pd.read_csv("retail_sales_dataset.csv")
    print("Raw Shape:", df.shape)
    print("\nFirst 5 rows:\n", df.head())
    df['date'] = pd.to_datetime(df['date'], errors='coerce')
    df = df.dropna(subset=['date'])
    num_cols = df.select_dtypes(include=[np.number]).columns
    df[num_cols] = df[num_cols].fillna(0)
    df = df.drop_duplicates()
    df = df.sort_values(by=['product_id', 'date'])
    print("\nAfter Cleaning Shape:", df.shape)
    print("\nColumns:", df.columns.tolist())
    df['units_sold_ma7'] = df.groupby('product_id')['units_sold'].transform(lambda x: x.rolling(7,1).mean())
    df['lag_1'] = df.groupby('product_id')['units_sold'].shift(1)
    df['revenue'] = df['units_sold'] * df['price']
    daily_sales = df.groupby('date')['units_sold'].sum().reset_index()
    plt.figure(figsize=(10,4))
    plt.plot(daily_sales['date'], daily_sales['units_sold'])
    plt.title("Daily Total Units Sold")
    plt.xlabel("Date")
    plt.ylabel("Units Sold")
    plt.show()
    df['month'] = df['date'].dt.to_period('M')
    monthly_sales = df.groupby('month')['units_sold'].sum().reset_index()
    plt.figure(figsize=(10,4))
    plt.plot(monthly_sales['month'].astype(str), monthly_sales['units_sold'])
    plt.title("Monthly Units Sold")
    plt.xticks(rotation=45)
    plt.show()
    cat_sales = df.groupby('category')['units_sold'].sum().sort_values(ascending=False)
    plt.figure(figsize=(8,4))
    sns.barplot(x=cat_sales.index, y=cat_sales.values)
    plt.title("Category-wise Total Units Sold")
    plt.xticks(rotation=45)
    plt.show()
    season_sales = df.groupby('season')['units_sold'].sum()
    plt.figure(figsize=(6,4))
    season_sales.plot(kind='bar', color='skyblue')
    plt.title("Season-wise Units Sold")
    plt.show()
    weather_sales = df.groupby('weather')['units_sold'].sum()
    plt.figure(figsize=(6,4))
    weather_sales.plot(kind='bar', color='orange')
    plt.title("Weather-wise Units Sold")
    plt.show()
    top_products = df.groupby('product_id')['units_sold'].sum().nlargest(10)
    plt.figure(figsize=(10,4))
    top_products.plot(kind='bar', color='green')
    plt.title("Top 10 Best Selling Products")
    plt.show()
    plt.figure(figsize=(6,4))
    sns.scatterplot(x='discount(%)', y='units_sold', data=df)
    plt.title("Discount vs Units Sold")
    plt.show()
    promo_sales = df.groupby('promotion')['units_sold'].mean()
    plt.figure(figsize=(6,4))
    promo_sales.plot(kind='bar', color='purple')
    plt.title("Average Units Sold - With vs Without Promotion")
    plt.show()
    holiday_sales = df.groupby('holiday')['units_sold'].mean()
    plt.figure(figsize=(6,4))
    holiday_sales.plot(kind='bar', color='red')
    plt.title("Average Units Sold - Holiday vs Non-Holiday")
    plt.show()
    plt.figure(figsize=(6,4))
    sns.histplot(df['price'], bins=30, kde=True)
    plt.title("Price Distribution")
    plt.show()
    revenue_daily = df.groupby('date')['revenue'].sum().reset_index()
    plt.figure(figsize=(10,4))
    plt.plot(revenue_daily['date'], revenue_daily['revenue'], color='brown')
    plt.title("Daily Total Revenue")
    plt.xlabel("Date")
    plt.ylabel("Revenue")
    plt.show()
    df.to_csv("cleaned_retail_sales.csv", index=False)
    print("\nPreprocessed data saved as cleaned_retail_sales.csv")

if __name__ == "__main__":
    main()
